/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'connect',
        'console',
        'console-shell',
        'page-not-found',
        'web-serial',
        'web-serial-util',
        'web-serial-data-access',
        'web-serial-state',
        'example',
        'wifi',
        'dialogs',
        'unsupported-browser',
        'editor',
        'terminal',
        'chirimen-panel',
        'pin-assign-panel',
        'shared-ui',
        'shared-guards',
        'shared-types',
        'shared-util',
        'i2cdetect',
        'i2cdetect-ui',
        'i2cdetect-data-access',
        'i2cdetect-util',
        'workspace',
        'setup',
        'file-manager',
        'remote',
      ],
    ],
  },
};
