packages:
  - 'apps/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx

# Malicious releases are often detected and removed within a week.
# 7 days x 24h x 60 min
minimumReleaseAge: 10080
